name: First Challenge
on: [push, workflow_dispatch]

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3 # pull repo code into the runner so it can find package.json

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18'

          - name: Install dependencies
            run: npm ci
          - name: run lint
            run: npm run lint

    